language: objective-c
osx_image: xcode8.1

rvm: 2.2.2
before_install:
    - gem install cocoapods -v '1.1.1'
    - pod setup > /dev/null    #/dev/null to prevent long logs
    - gem install xcpretty
#    - brew update
#    - brew outdated xctool || brew upgrade xctool
#    - git clone https://github.com/facebook/xctool.git #use this if current xctool is outdated
    
podfile: Podfile
xcode_workspace: AviasalesSDKTemplate.xcworkspace
xcode_scheme: AviasalesSDKTemplate
xcode_sdk: 
    - iphonesimulator
    
script:
   - xcodebuild -workspace AviasalesSDKTemplate.xcworkspace -scheme AviasalesSDKTemplate -sdk iphonesimulator build test | xcpretty
#    - xctool/xctool.sh  -workspace AviasalesSDKTemplate.xcworkspace -scheme AviasalesSDKTemplate -sdk iphonesimulator build test #use this if current xctool is outdated